version: '3.8'
services:
  whytalk:
    build:
        context: .
        dockerfile: dev.dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    networks:
       - whytalk-network
    working_dir: /app
    volumes:
      - .:/app


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
        - whytalk-network
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
networks:
    whytalk-network:
        name: whytalk-network
        driver: bridge
